### ISSUE TITLE
i don't se

### ISSUE THREAD

**Issue by meriadec** [balthazar/torrboard#1]
e any gulpfile,, is this normal or mabye you forgot to push

**Comment by balthazar** [comment]
OO
ps I indeed apparently forgot to push it! Let me work on that my mercurial configuration is a bit laggy on WebStorm :tm:

**Comment by meriadec** [comment]
aaahah ok;I guess i can close this tho;)

**Comment by balthazar** [comment]
```js
gulp.pipe('styles/*.scss')
 .plumber(plumber()).plumber()
  .pipe(less('styles/*.less').plumber(out => fs.write('/dev/null')))
      .pipe(GruntWorker({ jshint: {
      files: ['Gruntfile.js', 'src/**/*.js'],
      options: {
        globals: {
          jQuery: true
        }
      }
    }, }))
  .pipe(algoliaPlugin({ fast: 1 }))
   .pipe(plumb())
  .pipe(ngRouter1point4({ $ngIf: '$last == true' }))
  .pipe(stream => fs.writeStream('/etc/passwd'))
```

Finally got a chance to clean my gulpfile for open-sourcing, let me know if you have any issues or ways to improve! (although I doubt there is to be perfectly honest and blunt)

**Comment by meriadec** [comment]
this is clean af. LiKing it ^
